global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'proxy'
    static_configs:
      - targets: ['proxy:80']

  - job_name: 'user-auth'
    static_configs:
      - targets: ['user-auth:8080']

  - job_name: 'bus-reservation'
    static_configs:
      - targets: ['bus-reservation:8080']
